/* tslint:disable */
/* eslint-disable */
/**
 * you-comments backend API
 * backend API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/all-api';
export * from './apis/channel-api';
export * from './apis/movies-api';
export * from './apis/users-api';

