/* tslint:disable */
/* eslint-disable */
/**
 * you-comments backend API
 * backend API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CommentsList } from '../models';
import { DateRanges } from '../models';
/**
 * AllApi - axios parameter creator
 * @export
 */
export const AllApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 全体情報の取得
         * @param {DateRanges} [xDataRanges] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        allGet: async (xDataRanges?: DateRanges, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xDataRanges !== undefined && xDataRanges !== null) {
                localVarHeaderParameter['X-DataRanges'] = String(JSON.stringify(xDataRanges));
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AllApi - functional programming interface
 * @export
 */
export const AllApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 全体情報の取得
         * @param {DateRanges} [xDataRanges] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async allGet(xDataRanges?: DateRanges, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CommentsList>>> {
            const localVarAxiosArgs = await AllApiAxiosParamCreator(configuration).allGet(xDataRanges, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AllApi - factory interface
 * @export
 */
export const AllApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 全体情報の取得
         * @param {DateRanges} [xDataRanges] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async allGet(xDataRanges?: DateRanges, options?: AxiosRequestConfig): Promise<AxiosResponse<CommentsList>> {
            return AllApiFp(configuration).allGet(xDataRanges, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AllApi - object-oriented interface
 * @export
 * @class AllApi
 * @extends {BaseAPI}
 */
export class AllApi extends BaseAPI {
    /**
     * 
     * @summary 全体情報の取得
     * @param {DateRanges} [xDataRanges] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AllApi
     */
    public async allGet(xDataRanges?: DateRanges, options?: AxiosRequestConfig) : Promise<AxiosResponse<CommentsList>> {
        return AllApiFp(this.configuration).allGet(xDataRanges, options).then((request) => request(this.axios, this.basePath));
    }
}
