/* tslint:disable */
/* eslint-disable */
/**
 * you-comments backend API
 * backend API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Comments } from '../models';
import { Movie } from '../models';
/**
 * MoviesApi - axios parameter creator
 * @export
 */
export const MoviesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 動画のコメント群の取得
         * @param {string} movieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        movieCommentsMovieIdGet: async (movieId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'movieId' is not null or undefined
            if (movieId === null || movieId === undefined) {
                throw new RequiredError('movieId','Required parameter movieId was null or undefined when calling movieCommentsMovieIdGet.');
            }
            const localVarPath = `/movie_comments/{movieId}`
                .replace(`{${"movieId"}}`, encodeURIComponent(String(movieId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 動画情報の取得
         * @param {string} movieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        moviesMovieIdGet: async (movieId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'movieId' is not null or undefined
            if (movieId === null || movieId === undefined) {
                throw new RequiredError('movieId','Required parameter movieId was null or undefined when calling moviesMovieIdGet.');
            }
            const localVarPath = `/movies/{movieId}`
                .replace(`{${"movieId"}}`, encodeURIComponent(String(movieId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MoviesApi - functional programming interface
 * @export
 */
export const MoviesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 動画のコメント群の取得
         * @param {string} movieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async movieCommentsMovieIdGet(movieId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Comments>>> {
            const localVarAxiosArgs = await MoviesApiAxiosParamCreator(configuration).movieCommentsMovieIdGet(movieId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 動画情報の取得
         * @param {string} movieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async moviesMovieIdGet(movieId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Movie>>> {
            const localVarAxiosArgs = await MoviesApiAxiosParamCreator(configuration).moviesMovieIdGet(movieId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MoviesApi - factory interface
 * @export
 */
export const MoviesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 動画のコメント群の取得
         * @param {string} movieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async movieCommentsMovieIdGet(movieId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Comments>> {
            return MoviesApiFp(configuration).movieCommentsMovieIdGet(movieId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 動画情報の取得
         * @param {string} movieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async moviesMovieIdGet(movieId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Movie>> {
            return MoviesApiFp(configuration).moviesMovieIdGet(movieId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MoviesApi - object-oriented interface
 * @export
 * @class MoviesApi
 * @extends {BaseAPI}
 */
export class MoviesApi extends BaseAPI {
    /**
     * 
     * @summary 動画のコメント群の取得
     * @param {string} movieId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoviesApi
     */
    public async movieCommentsMovieIdGet(movieId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Comments>> {
        return MoviesApiFp(this.configuration).movieCommentsMovieIdGet(movieId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 動画情報の取得
     * @param {string} movieId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoviesApi
     */
    public async moviesMovieIdGet(movieId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Movie>> {
        return MoviesApiFp(this.configuration).moviesMovieIdGet(movieId, options).then((request) => request(this.axios, this.basePath));
    }
}
