/* tslint:disable */
/* eslint-disable */
/**
 * you-comments backend API
 * backend API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comment } from './comment';
/**
 * 
 * @export
 * @interface Movie
 */
export interface Movie {
    /**
     * 
     * @type {string}
     * @memberof Movie
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Movie
     */
    movieId: string;
    /**
     * 
     * @type {string}
     * @memberof Movie
     */
    uploadUserId: string;
    /**
     * 
     * @type {string}
     * @memberof Movie
     */
    channelId: string;
    /**
     * 
     * @type {Comment}
     * @memberof Movie
     */
    bestComment?: Comment;
}
